/**
 * Detects if a key input chunk is a complete or partial SGR mouse reporting escape sequence.
 * These escape sequences are generated by terminal mouse reporting (modes 1003, 1006, 1016)
 * and can leak into standard input handlers, appearing as garbage text like "<35;72;37M".
 *
 * Handles both complete sequences (\x1b[<35;72;37M) and split fragments that arrive across
 * multiple useInput() callbacks due to chunked stdin reads in modern terminals (Ghostty, WezTerm, iTerm2).
 */
const COMPLETE_SGR = /^\x1b\[<\d+;\d+;\d+[Mm]$/;
const COMPLETE_X10 = /^\x1b\[M...$/;
const COORD_CHUNK = /^<?\d+;\d+;\d+[Mm]$/;
const COORD_FRAGMENT_START = /^\d+;\d+;\d+/; // e.g. "35;72;37" before final M/m
const COORD_FRAGMENT_LEFT_BRACKET = /^<\d*$/; // e.g. "<" or "<35"
const COORD_FRAGMENT_DIGITS = /^\d+;\d+$/; // e.g. "35;72" (middle chunk)
const COORD_FRAGMENT_TAIL = /^\d+[Mm]$/; // e.g. "37M" or "25M" (last chunk)
const COORD_BARE_TAIL = /^[Mm]$/; // bare M/m tail
const MODIFIED_KEY_TAIL = /^\d+;\d+~\??$/; // e.g. "13;2~" — not mouse, but verify
const BRACKET_PUNCT = /^[\[<]$/; // bare punctuation that might start a sequence

export function isMouseSequence(k: string): boolean {
	if (!k) return false;

	// Complete sequences
	if (k.startsWith("\x1b[M") || k.startsWith("\x1b[<")) return true;
	if (COMPLETE_SGR.test(k) || COMPLETE_X10.test(k)) return true;

	// Full coordinate chunks
	if (COORD_CHUNK.test(k)) return true;

	// Partial fragments produced by chunked stdin reads
	if (COORD_FRAGMENT_START.test(k)) return true;
	if (COORD_FRAGMENT_LEFT_BRACKET.test(k)) return true;
	if (COORD_FRAGMENT_DIGITS.test(k)) return true;
	if (COORD_FRAGMENT_TAIL.test(k)) return true;
	// Bare M/m tail — single-char SGR release leak.
	// Single-char M/m is not a printable key the user types intentionally.
	if (COORD_BARE_TAIL.test(k)) return true;

	// Fallback: contains "<" and ends with M/m
	if (k.includes("<") && (k.endsWith("M") || k.endsWith("m"))) return true;

	return false;
}

/**
 * Determines if a string is a partial SGR mouse sequence fragment that could be
 * completed by appending more data. Used by the input buffer to decide whether
 * to flush immediately or wait for more input.
 */
export function isMouseSequenceFragment(k: string): boolean {
	if (!k) return false;
	if (BRACKET_PUNCT.test(k)) return true;
	if (COORD_FRAGMENT_LEFT_BRACKET.test(k)) return true;
	if (COORD_FRAGMENT_DIGITS.test(k)) return true;
	// Avoid false positives on numbers like "35" alone
	return false;
}

/**
 * Determines if a string looks like the tail end of a mouse sequence
 * (so the buffer should be flushed+discarded).
 */
export function isMouseSequenceTail(k: string): boolean {
	if (!k) return false;
	if (COORD_FRAGMENT_TAIL.test(k)) return true;
	if (COORD_FRAGMENT_START.test(k)) return true;
	return false;
}
